### ISSUE TITLE
Update red-base

### ISSUE THREAD

**Issue by kaelig** [Shopify/polaris-tokens#1]
From `#ED6347` to `#DE3618`.

See https://github.com/Shopify/polaris-ux/issues/87 for the reasoning behind this change.

Open issues / mention people in:
- [x] polaris-tokens Shopify/polaris-tokens#1 See fb4c7a451a02a9ae761598752107414f062c63c6
- [x] polaris-rails Shopify/polaris-rails#1241
- [x] polaris-react Shopify/polaris-react#1072 https://github.com/Shopify/polaris-react/pull/1076
- [x] polaris-styleguide https://github.com/Shopify/polaris-styleguide/pull/1298
- [x] mobile foundations https://github.com/Shopify/mobile-shopify/issues/9433
- [x] Sketch UI Kit
- [x] Icon library [See commit](https://app.goabstract.com/projects/c293c340-3b22-11e7-a15d-97f6a02bce93/branches/master/commits/a52dadf277a3be717bca57f01244540687b0479c)
- [x] Sketch palette
- [x] Invision DSM
